//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServTests.CalcService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://edu.softserve.com/", ConfigurationName="CalcService.CalcSEI")]
    public interface CalcSEI {
        
        // CODEGEN: Контракт генерации сообщений с пространством имен частей сообщения () не соответствует значению по умолчанию (http://edu.softserve.com/).
        [System.ServiceModel.OperationContractAttribute(Action="urn:Mod", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WebServTests.CalcService.modResponse mod(WebServTests.CalcService.mod request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Mod", ReplyAction="*")]
        System.Threading.Tasks.Task<WebServTests.CalcService.modResponse> modAsync(WebServTests.CalcService.mod request);
        
        // CODEGEN: Контракт генерации сообщений с пространством имен частей сообщения () не соответствует значению по умолчанию (http://edu.softserve.com/).
        [System.ServiceModel.OperationContractAttribute(Action="urn:Add", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WebServTests.CalcService.addResponse add(WebServTests.CalcService.add request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Add", ReplyAction="*")]
        System.Threading.Tasks.Task<WebServTests.CalcService.addResponse> addAsync(WebServTests.CalcService.add request);
        
        // CODEGEN: Контракт генерации сообщений с пространством имен частей сообщения () не соответствует значению по умолчанию (http://edu.softserve.com/).
        [System.ServiceModel.OperationContractAttribute(Action="urn:Div", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WebServTests.CalcService.divResponse div(WebServTests.CalcService.div request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Div", ReplyAction="*")]
        System.Threading.Tasks.Task<WebServTests.CalcService.divResponse> divAsync(WebServTests.CalcService.div request);
        
        // CODEGEN: Контракт генерации сообщений с пространством имен частей сообщения () не соответствует значению по умолчанию (http://edu.softserve.com/).
        [System.ServiceModel.OperationContractAttribute(Action="urn:Sub", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WebServTests.CalcService.subResponse sub(WebServTests.CalcService.sub request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Sub", ReplyAction="*")]
        System.Threading.Tasks.Task<WebServTests.CalcService.subResponse> subAsync(WebServTests.CalcService.sub request);
        
        // CODEGEN: Контракт генерации сообщений с пространством имен частей сообщения () не соответствует значению по умолчанию (http://edu.softserve.com/).
        [System.ServiceModel.OperationContractAttribute(Action="urn:Factorial", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WebServTests.CalcService.factorialResponse factorial(WebServTests.CalcService.factorial request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Factorial", ReplyAction="*")]
        System.Threading.Tasks.Task<WebServTests.CalcService.factorialResponse> factorialAsync(WebServTests.CalcService.factorial request);
        
        // CODEGEN: Контракт генерации сообщений с пространством имен частей сообщения () не соответствует значению по умолчанию (http://edu.softserve.com/).
        [System.ServiceModel.OperationContractAttribute(Action="urn:Mul", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WebServTests.CalcService.mulResponse mul(WebServTests.CalcService.mul request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Mul", ReplyAction="*")]
        System.Threading.Tasks.Task<WebServTests.CalcService.mulResponse> mulAsync(WebServTests.CalcService.mul request);
        
        // CODEGEN: Контракт генерации сообщений с пространством имен частей сообщения () не соответствует значению по умолчанию (http://edu.softserve.com/).
        [System.ServiceModel.OperationContractAttribute(Action="urn:Sqr", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WebServTests.CalcService.sqrResponse sqr(WebServTests.CalcService.sqr request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Sqr", ReplyAction="*")]
        System.Threading.Tasks.Task<WebServTests.CalcService.sqrResponse> sqrAsync(WebServTests.CalcService.sqr request);
        
        // CODEGEN: Контракт генерации сообщений с пространством имен частей сообщения () не соответствует значению по умолчанию (http://edu.softserve.com/).
        [System.ServiceModel.OperationContractAttribute(Action="urn:Sqrt", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WebServTests.CalcService.sqrtResponse sqrt(WebServTests.CalcService.sqrt request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Sqrt", ReplyAction="*")]
        System.Threading.Tasks.Task<WebServTests.CalcService.sqrtResponse> sqrtAsync(WebServTests.CalcService.sqrt request);
        
        // CODEGEN: Контракт генерации сообщений с именем arg0 из пространства имен  не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="urn:About", ReplyAction="*")]
        WebServTests.CalcService.aboutResponse about(WebServTests.CalcService.about request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:About", ReplyAction="*")]
        System.Threading.Tasks.Task<WebServTests.CalcService.aboutResponse> aboutAsync(WebServTests.CalcService.about request);
        
        // CODEGEN: Контракт генерации сообщений с пространством имен частей сообщения () не соответствует значению по умолчанию (http://edu.softserve.com/).
        [System.ServiceModel.OperationContractAttribute(Action="urn:Pow", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WebServTests.CalcService.powResponse pow(WebServTests.CalcService.pow request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Pow", ReplyAction="*")]
        System.Threading.Tasks.Task<WebServTests.CalcService.powResponse> powAsync(WebServTests.CalcService.pow request);
        
        // CODEGEN: Контракт генерации сообщений с именем упаковщика (divResponse1) сообщения div1Response не соответствует значению по умолчанию (div1).
        [System.ServiceModel.OperationContractAttribute(Action="urn:Div1", ReplyAction="*")]
        WebServTests.CalcService.div1Response div1(WebServTests.CalcService.div1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Div1", ReplyAction="*")]
        System.Threading.Tasks.Task<WebServTests.CalcService.div1Response> div1Async(WebServTests.CalcService.div1 request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="mod", WrapperNamespace="http://edu.softserve.com/", IsWrapped=true)]
    public partial class mod {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public int arg1;
        
        public mod() {
        }
        
        public mod(int arg0, int arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modResponse", WrapperNamespace="http://edu.softserve.com/", IsWrapped=true)]
    public partial class modResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int @return;
        
        public modResponse() {
        }
        
        public modResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="add", WrapperNamespace="http://edu.softserve.com/", IsWrapped=true)]
    public partial class add {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public double arg1;
        
        public add() {
        }
        
        public add(double arg0, double arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addResponse", WrapperNamespace="http://edu.softserve.com/", IsWrapped=true)]
    public partial class addResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double @return;
        
        public addResponse() {
        }
        
        public addResponse(double @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="div", WrapperNamespace="http://edu.softserve.com/", IsWrapped=true)]
    public partial class div {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public double arg1;
        
        public div() {
        }
        
        public div(double arg0, double arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="divResponse", WrapperNamespace="http://edu.softserve.com/", IsWrapped=true)]
    public partial class divResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double @return;
        
        public divResponse() {
        }
        
        public divResponse(double @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sub", WrapperNamespace="http://edu.softserve.com/", IsWrapped=true)]
    public partial class sub {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public double arg1;
        
        public sub() {
        }
        
        public sub(double arg0, double arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="subResponse", WrapperNamespace="http://edu.softserve.com/", IsWrapped=true)]
    public partial class subResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double @return;
        
        public subResponse() {
        }
        
        public subResponse(double @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="factorial", WrapperNamespace="http://edu.softserve.com/", IsWrapped=true)]
    public partial class factorial {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int arg0;
        
        public factorial() {
        }
        
        public factorial(int arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="factorialResponse", WrapperNamespace="http://edu.softserve.com/", IsWrapped=true)]
    public partial class factorialResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public long @return;
        
        public factorialResponse() {
        }
        
        public factorialResponse(long @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="mul", WrapperNamespace="http://edu.softserve.com/", IsWrapped=true)]
    public partial class mul {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public double arg1;
        
        public mul() {
        }
        
        public mul(double arg0, double arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="mulResponse", WrapperNamespace="http://edu.softserve.com/", IsWrapped=true)]
    public partial class mulResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double @return;
        
        public mulResponse() {
        }
        
        public mulResponse(double @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sqr", WrapperNamespace="http://edu.softserve.com/", IsWrapped=true)]
    public partial class sqr {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double arg0;
        
        public sqr() {
        }
        
        public sqr(double arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sqrResponse", WrapperNamespace="http://edu.softserve.com/", IsWrapped=true)]
    public partial class sqrResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double @return;
        
        public sqrResponse() {
        }
        
        public sqrResponse(double @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sqrt", WrapperNamespace="http://edu.softserve.com/", IsWrapped=true)]
    public partial class sqrt {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double arg0;
        
        public sqrt() {
        }
        
        public sqrt(double arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sqrtResponse", WrapperNamespace="http://edu.softserve.com/", IsWrapped=true)]
    public partial class sqrtResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double @return;
        
        public sqrtResponse() {
        }
        
        public sqrtResponse(double @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class about {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="about", Namespace="http://edu.softserve.com/", Order=0)]
        public WebServTests.CalcService.aboutBody Body;
        
        public about() {
        }
        
        public about(WebServTests.CalcService.aboutBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class aboutBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        public aboutBody() {
        }
        
        public aboutBody(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class aboutResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="aboutResponse", Namespace="http://edu.softserve.com/", Order=0)]
        public WebServTests.CalcService.aboutResponseBody Body;
        
        public aboutResponse() {
        }
        
        public aboutResponse(WebServTests.CalcService.aboutResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class aboutResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public aboutResponseBody() {
        }
        
        public aboutResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="pow", WrapperNamespace="http://edu.softserve.com/", IsWrapped=true)]
    public partial class pow {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public double arg1;
        
        public pow() {
        }
        
        public pow(double arg0, double arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="powResponse", WrapperNamespace="http://edu.softserve.com/", IsWrapped=true)]
    public partial class powResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double @return;
        
        public powResponse() {
        }
        
        public powResponse(double @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="div1", WrapperNamespace="http://edu.softserve.com/", IsWrapped=true)]
    public partial class div1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public int arg1;
        
        public div1() {
        }
        
        public div1(int arg0, int arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="divResponse1", WrapperNamespace="http://edu.softserve.com/", IsWrapped=true)]
    public partial class div1Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int @return;
        
        public div1Response() {
        }
        
        public div1Response(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CalcSEIChannel : WebServTests.CalcService.CalcSEI, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalcSEIClient : System.ServiceModel.ClientBase<WebServTests.CalcService.CalcSEI>, WebServTests.CalcService.CalcSEI {
        
        public CalcSEIClient() {
        }
        
        public CalcSEIClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CalcSEIClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalcSEIClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalcSEIClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServTests.CalcService.modResponse WebServTests.CalcService.CalcSEI.mod(WebServTests.CalcService.mod request) {
            return base.Channel.mod(request);
        }
        
        public int mod(int arg0, int arg1) {
            WebServTests.CalcService.mod inValue = new WebServTests.CalcService.mod();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            WebServTests.CalcService.modResponse retVal = ((WebServTests.CalcService.CalcSEI)(this)).mod(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebServTests.CalcService.modResponse> WebServTests.CalcService.CalcSEI.modAsync(WebServTests.CalcService.mod request) {
            return base.Channel.modAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebServTests.CalcService.modResponse> modAsync(int arg0, int arg1) {
            WebServTests.CalcService.mod inValue = new WebServTests.CalcService.mod();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((WebServTests.CalcService.CalcSEI)(this)).modAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServTests.CalcService.addResponse WebServTests.CalcService.CalcSEI.add(WebServTests.CalcService.add request) {
            return base.Channel.add(request);
        }
        
        public double add(double arg0, double arg1) {
            WebServTests.CalcService.add inValue = new WebServTests.CalcService.add();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            WebServTests.CalcService.addResponse retVal = ((WebServTests.CalcService.CalcSEI)(this)).add(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebServTests.CalcService.addResponse> WebServTests.CalcService.CalcSEI.addAsync(WebServTests.CalcService.add request) {
            return base.Channel.addAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebServTests.CalcService.addResponse> addAsync(double arg0, double arg1) {
            WebServTests.CalcService.add inValue = new WebServTests.CalcService.add();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((WebServTests.CalcService.CalcSEI)(this)).addAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServTests.CalcService.divResponse WebServTests.CalcService.CalcSEI.div(WebServTests.CalcService.div request) {
            return base.Channel.div(request);
        }
        
        public double div(double arg0, double arg1) {
            WebServTests.CalcService.div inValue = new WebServTests.CalcService.div();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            WebServTests.CalcService.divResponse retVal = ((WebServTests.CalcService.CalcSEI)(this)).div(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebServTests.CalcService.divResponse> WebServTests.CalcService.CalcSEI.divAsync(WebServTests.CalcService.div request) {
            return base.Channel.divAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebServTests.CalcService.divResponse> divAsync(double arg0, double arg1) {
            WebServTests.CalcService.div inValue = new WebServTests.CalcService.div();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((WebServTests.CalcService.CalcSEI)(this)).divAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServTests.CalcService.subResponse WebServTests.CalcService.CalcSEI.sub(WebServTests.CalcService.sub request) {
            return base.Channel.sub(request);
        }
        
        public double sub(double arg0, double arg1) {
            WebServTests.CalcService.sub inValue = new WebServTests.CalcService.sub();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            WebServTests.CalcService.subResponse retVal = ((WebServTests.CalcService.CalcSEI)(this)).sub(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebServTests.CalcService.subResponse> WebServTests.CalcService.CalcSEI.subAsync(WebServTests.CalcService.sub request) {
            return base.Channel.subAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebServTests.CalcService.subResponse> subAsync(double arg0, double arg1) {
            WebServTests.CalcService.sub inValue = new WebServTests.CalcService.sub();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((WebServTests.CalcService.CalcSEI)(this)).subAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServTests.CalcService.factorialResponse WebServTests.CalcService.CalcSEI.factorial(WebServTests.CalcService.factorial request) {
            return base.Channel.factorial(request);
        }
        
        public long factorial(int arg0) {
            WebServTests.CalcService.factorial inValue = new WebServTests.CalcService.factorial();
            inValue.arg0 = arg0;
            WebServTests.CalcService.factorialResponse retVal = ((WebServTests.CalcService.CalcSEI)(this)).factorial(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebServTests.CalcService.factorialResponse> WebServTests.CalcService.CalcSEI.factorialAsync(WebServTests.CalcService.factorial request) {
            return base.Channel.factorialAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebServTests.CalcService.factorialResponse> factorialAsync(int arg0) {
            WebServTests.CalcService.factorial inValue = new WebServTests.CalcService.factorial();
            inValue.arg0 = arg0;
            return ((WebServTests.CalcService.CalcSEI)(this)).factorialAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServTests.CalcService.mulResponse WebServTests.CalcService.CalcSEI.mul(WebServTests.CalcService.mul request) {
            return base.Channel.mul(request);
        }
        
        public double mul(double arg0, double arg1) {
            WebServTests.CalcService.mul inValue = new WebServTests.CalcService.mul();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            WebServTests.CalcService.mulResponse retVal = ((WebServTests.CalcService.CalcSEI)(this)).mul(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebServTests.CalcService.mulResponse> WebServTests.CalcService.CalcSEI.mulAsync(WebServTests.CalcService.mul request) {
            return base.Channel.mulAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebServTests.CalcService.mulResponse> mulAsync(double arg0, double arg1) {
            WebServTests.CalcService.mul inValue = new WebServTests.CalcService.mul();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((WebServTests.CalcService.CalcSEI)(this)).mulAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServTests.CalcService.sqrResponse WebServTests.CalcService.CalcSEI.sqr(WebServTests.CalcService.sqr request) {
            return base.Channel.sqr(request);
        }
        
        public double sqr(double arg0) {
            WebServTests.CalcService.sqr inValue = new WebServTests.CalcService.sqr();
            inValue.arg0 = arg0;
            WebServTests.CalcService.sqrResponse retVal = ((WebServTests.CalcService.CalcSEI)(this)).sqr(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebServTests.CalcService.sqrResponse> WebServTests.CalcService.CalcSEI.sqrAsync(WebServTests.CalcService.sqr request) {
            return base.Channel.sqrAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebServTests.CalcService.sqrResponse> sqrAsync(double arg0) {
            WebServTests.CalcService.sqr inValue = new WebServTests.CalcService.sqr();
            inValue.arg0 = arg0;
            return ((WebServTests.CalcService.CalcSEI)(this)).sqrAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServTests.CalcService.sqrtResponse WebServTests.CalcService.CalcSEI.sqrt(WebServTests.CalcService.sqrt request) {
            return base.Channel.sqrt(request);
        }
        
        public double sqrt(double arg0) {
            WebServTests.CalcService.sqrt inValue = new WebServTests.CalcService.sqrt();
            inValue.arg0 = arg0;
            WebServTests.CalcService.sqrtResponse retVal = ((WebServTests.CalcService.CalcSEI)(this)).sqrt(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebServTests.CalcService.sqrtResponse> WebServTests.CalcService.CalcSEI.sqrtAsync(WebServTests.CalcService.sqrt request) {
            return base.Channel.sqrtAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebServTests.CalcService.sqrtResponse> sqrtAsync(double arg0) {
            WebServTests.CalcService.sqrt inValue = new WebServTests.CalcService.sqrt();
            inValue.arg0 = arg0;
            return ((WebServTests.CalcService.CalcSEI)(this)).sqrtAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServTests.CalcService.aboutResponse WebServTests.CalcService.CalcSEI.about(WebServTests.CalcService.about request) {
            return base.Channel.about(request);
        }
        
        public string about(string arg0) {
            WebServTests.CalcService.about inValue = new WebServTests.CalcService.about();
            inValue.Body = new WebServTests.CalcService.aboutBody();
            inValue.Body.arg0 = arg0;
            WebServTests.CalcService.aboutResponse retVal = ((WebServTests.CalcService.CalcSEI)(this)).about(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebServTests.CalcService.aboutResponse> WebServTests.CalcService.CalcSEI.aboutAsync(WebServTests.CalcService.about request) {
            return base.Channel.aboutAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebServTests.CalcService.aboutResponse> aboutAsync(string arg0) {
            WebServTests.CalcService.about inValue = new WebServTests.CalcService.about();
            inValue.Body = new WebServTests.CalcService.aboutBody();
            inValue.Body.arg0 = arg0;
            return ((WebServTests.CalcService.CalcSEI)(this)).aboutAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServTests.CalcService.powResponse WebServTests.CalcService.CalcSEI.pow(WebServTests.CalcService.pow request) {
            return base.Channel.pow(request);
        }
        
        public double pow(double arg0, double arg1) {
            WebServTests.CalcService.pow inValue = new WebServTests.CalcService.pow();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            WebServTests.CalcService.powResponse retVal = ((WebServTests.CalcService.CalcSEI)(this)).pow(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebServTests.CalcService.powResponse> WebServTests.CalcService.CalcSEI.powAsync(WebServTests.CalcService.pow request) {
            return base.Channel.powAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebServTests.CalcService.powResponse> powAsync(double arg0, double arg1) {
            WebServTests.CalcService.pow inValue = new WebServTests.CalcService.pow();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((WebServTests.CalcService.CalcSEI)(this)).powAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServTests.CalcService.div1Response WebServTests.CalcService.CalcSEI.div1(WebServTests.CalcService.div1 request) {
            return base.Channel.div1(request);
        }
        
        public int div1(int arg0, int arg1) {
            WebServTests.CalcService.div1 inValue = new WebServTests.CalcService.div1();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            WebServTests.CalcService.div1Response retVal = ((WebServTests.CalcService.CalcSEI)(this)).div1(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebServTests.CalcService.div1Response> WebServTests.CalcService.CalcSEI.div1Async(WebServTests.CalcService.div1 request) {
            return base.Channel.div1Async(request);
        }
        
        public System.Threading.Tasks.Task<WebServTests.CalcService.div1Response> div1Async(int arg0, int arg1) {
            WebServTests.CalcService.div1 inValue = new WebServTests.CalcService.div1();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((WebServTests.CalcService.CalcSEI)(this)).div1Async(inValue);
        }
    }
}
