//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebService.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://edu.softserve.com/", ConfigurationName="ServiceReference1.CalcSEI")]
    public interface CalcSEI {
        
        // CODEGEN: Контракт генерации сообщений с пространством имен частей сообщения () не соответствует значению по умолчанию (http://edu.softserve.com/).
        [System.ServiceModel.OperationContractAttribute(Action="urn:Mod", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WebService.ServiceReference1.modResponse mod(WebService.ServiceReference1.mod request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Mod", ReplyAction="*")]
        System.Threading.Tasks.Task<WebService.ServiceReference1.modResponse> modAsync(WebService.ServiceReference1.mod request);
        
        // CODEGEN: Контракт генерации сообщений с пространством имен частей сообщения () не соответствует значению по умолчанию (http://edu.softserve.com/).
        [System.ServiceModel.OperationContractAttribute(Action="urn:Add", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WebService.ServiceReference1.addResponse add(WebService.ServiceReference1.add request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Add", ReplyAction="*")]
        System.Threading.Tasks.Task<WebService.ServiceReference1.addResponse> addAsync(WebService.ServiceReference1.add request);
        
        // CODEGEN: Контракт генерации сообщений с пространством имен частей сообщения () не соответствует значению по умолчанию (http://edu.softserve.com/).
        [System.ServiceModel.OperationContractAttribute(Action="urn:Div", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WebService.ServiceReference1.divResponse div(WebService.ServiceReference1.div request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Div", ReplyAction="*")]
        System.Threading.Tasks.Task<WebService.ServiceReference1.divResponse> divAsync(WebService.ServiceReference1.div request);
        
        // CODEGEN: Контракт генерации сообщений с пространством имен частей сообщения () не соответствует значению по умолчанию (http://edu.softserve.com/).
        [System.ServiceModel.OperationContractAttribute(Action="urn:Sub", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WebService.ServiceReference1.subResponse sub(WebService.ServiceReference1.sub request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Sub", ReplyAction="*")]
        System.Threading.Tasks.Task<WebService.ServiceReference1.subResponse> subAsync(WebService.ServiceReference1.sub request);
        
        // CODEGEN: Контракт генерации сообщений с пространством имен частей сообщения () не соответствует значению по умолчанию (http://edu.softserve.com/).
        [System.ServiceModel.OperationContractAttribute(Action="urn:Factorial", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WebService.ServiceReference1.factorialResponse factorial(WebService.ServiceReference1.factorial request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Factorial", ReplyAction="*")]
        System.Threading.Tasks.Task<WebService.ServiceReference1.factorialResponse> factorialAsync(WebService.ServiceReference1.factorial request);
        
        // CODEGEN: Контракт генерации сообщений с пространством имен частей сообщения () не соответствует значению по умолчанию (http://edu.softserve.com/).
        [System.ServiceModel.OperationContractAttribute(Action="urn:Mul", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WebService.ServiceReference1.mulResponse mul(WebService.ServiceReference1.mul request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Mul", ReplyAction="*")]
        System.Threading.Tasks.Task<WebService.ServiceReference1.mulResponse> mulAsync(WebService.ServiceReference1.mul request);
        
        // CODEGEN: Контракт генерации сообщений с пространством имен частей сообщения () не соответствует значению по умолчанию (http://edu.softserve.com/).
        [System.ServiceModel.OperationContractAttribute(Action="urn:Sqr", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WebService.ServiceReference1.sqrResponse sqr(WebService.ServiceReference1.sqr request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Sqr", ReplyAction="*")]
        System.Threading.Tasks.Task<WebService.ServiceReference1.sqrResponse> sqrAsync(WebService.ServiceReference1.sqr request);
        
        // CODEGEN: Контракт генерации сообщений с пространством имен частей сообщения () не соответствует значению по умолчанию (http://edu.softserve.com/).
        [System.ServiceModel.OperationContractAttribute(Action="urn:Sqrt", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WebService.ServiceReference1.sqrtResponse sqrt(WebService.ServiceReference1.sqrt request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Sqrt", ReplyAction="*")]
        System.Threading.Tasks.Task<WebService.ServiceReference1.sqrtResponse> sqrtAsync(WebService.ServiceReference1.sqrt request);
        
        // CODEGEN: Контракт генерации сообщений с именем arg0 из пространства имен  не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="urn:About", ReplyAction="*")]
        WebService.ServiceReference1.aboutResponse about(WebService.ServiceReference1.about request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:About", ReplyAction="*")]
        System.Threading.Tasks.Task<WebService.ServiceReference1.aboutResponse> aboutAsync(WebService.ServiceReference1.about request);
        
        // CODEGEN: Контракт генерации сообщений с пространством имен частей сообщения () не соответствует значению по умолчанию (http://edu.softserve.com/).
        [System.ServiceModel.OperationContractAttribute(Action="urn:Pow", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WebService.ServiceReference1.powResponse pow(WebService.ServiceReference1.pow request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Pow", ReplyAction="*")]
        System.Threading.Tasks.Task<WebService.ServiceReference1.powResponse> powAsync(WebService.ServiceReference1.pow request);
        
        // CODEGEN: Контракт генерации сообщений с именем упаковщика (divResponse1) сообщения div1Response не соответствует значению по умолчанию (div1).
        [System.ServiceModel.OperationContractAttribute(Action="urn:Div1", ReplyAction="*")]
        WebService.ServiceReference1.div1Response div1(WebService.ServiceReference1.div1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Div1", ReplyAction="*")]
        System.Threading.Tasks.Task<WebService.ServiceReference1.div1Response> div1Async(WebService.ServiceReference1.div1 request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="mod", WrapperNamespace="http://edu.softserve.com/", IsWrapped=true)]
    public partial class mod {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public int arg1;
        
        public mod() {
        }
        
        public mod(int arg0, int arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modResponse", WrapperNamespace="http://edu.softserve.com/", IsWrapped=true)]
    public partial class modResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int @return;
        
        public modResponse() {
        }
        
        public modResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="add", WrapperNamespace="http://edu.softserve.com/", IsWrapped=true)]
    public partial class add {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public double arg1;
        
        public add() {
        }
        
        public add(double arg0, double arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addResponse", WrapperNamespace="http://edu.softserve.com/", IsWrapped=true)]
    public partial class addResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double @return;
        
        public addResponse() {
        }
        
        public addResponse(double @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="div", WrapperNamespace="http://edu.softserve.com/", IsWrapped=true)]
    public partial class div {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public double arg1;
        
        public div() {
        }
        
        public div(double arg0, double arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="divResponse", WrapperNamespace="http://edu.softserve.com/", IsWrapped=true)]
    public partial class divResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double @return;
        
        public divResponse() {
        }
        
        public divResponse(double @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sub", WrapperNamespace="http://edu.softserve.com/", IsWrapped=true)]
    public partial class sub {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public double arg1;
        
        public sub() {
        }
        
        public sub(double arg0, double arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="subResponse", WrapperNamespace="http://edu.softserve.com/", IsWrapped=true)]
    public partial class subResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double @return;
        
        public subResponse() {
        }
        
        public subResponse(double @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="factorial", WrapperNamespace="http://edu.softserve.com/", IsWrapped=true)]
    public partial class factorial {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int arg0;
        
        public factorial() {
        }
        
        public factorial(int arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="factorialResponse", WrapperNamespace="http://edu.softserve.com/", IsWrapped=true)]
    public partial class factorialResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public long @return;
        
        public factorialResponse() {
        }
        
        public factorialResponse(long @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="mul", WrapperNamespace="http://edu.softserve.com/", IsWrapped=true)]
    public partial class mul {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public double arg1;
        
        public mul() {
        }
        
        public mul(double arg0, double arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="mulResponse", WrapperNamespace="http://edu.softserve.com/", IsWrapped=true)]
    public partial class mulResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double @return;
        
        public mulResponse() {
        }
        
        public mulResponse(double @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sqr", WrapperNamespace="http://edu.softserve.com/", IsWrapped=true)]
    public partial class sqr {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double arg0;
        
        public sqr() {
        }
        
        public sqr(double arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sqrResponse", WrapperNamespace="http://edu.softserve.com/", IsWrapped=true)]
    public partial class sqrResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double @return;
        
        public sqrResponse() {
        }
        
        public sqrResponse(double @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sqrt", WrapperNamespace="http://edu.softserve.com/", IsWrapped=true)]
    public partial class sqrt {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double arg0;
        
        public sqrt() {
        }
        
        public sqrt(double arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sqrtResponse", WrapperNamespace="http://edu.softserve.com/", IsWrapped=true)]
    public partial class sqrtResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double @return;
        
        public sqrtResponse() {
        }
        
        public sqrtResponse(double @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class about {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="about", Namespace="http://edu.softserve.com/", Order=0)]
        public WebService.ServiceReference1.aboutBody Body;
        
        public about() {
        }
        
        public about(WebService.ServiceReference1.aboutBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class aboutBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        public aboutBody() {
        }
        
        public aboutBody(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class aboutResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="aboutResponse", Namespace="http://edu.softserve.com/", Order=0)]
        public WebService.ServiceReference1.aboutResponseBody Body;
        
        public aboutResponse() {
        }
        
        public aboutResponse(WebService.ServiceReference1.aboutResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class aboutResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public aboutResponseBody() {
        }
        
        public aboutResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="pow", WrapperNamespace="http://edu.softserve.com/", IsWrapped=true)]
    public partial class pow {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public double arg1;
        
        public pow() {
        }
        
        public pow(double arg0, double arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="powResponse", WrapperNamespace="http://edu.softserve.com/", IsWrapped=true)]
    public partial class powResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double @return;
        
        public powResponse() {
        }
        
        public powResponse(double @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="div1", WrapperNamespace="http://edu.softserve.com/", IsWrapped=true)]
    public partial class div1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public int arg1;
        
        public div1() {
        }
        
        public div1(int arg0, int arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="divResponse1", WrapperNamespace="http://edu.softserve.com/", IsWrapped=true)]
    public partial class div1Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int @return;
        
        public div1Response() {
        }
        
        public div1Response(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CalcSEIChannel : WebService.ServiceReference1.CalcSEI, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalcSEIClient : System.ServiceModel.ClientBase<WebService.ServiceReference1.CalcSEI>, WebService.ServiceReference1.CalcSEI {
        
        public CalcSEIClient() {
        }
        
        public CalcSEIClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CalcSEIClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalcSEIClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalcSEIClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebService.ServiceReference1.modResponse WebService.ServiceReference1.CalcSEI.mod(WebService.ServiceReference1.mod request) {
            return base.Channel.mod(request);
        }
        
        public int mod(int arg0, int arg1) {
            WebService.ServiceReference1.mod inValue = new WebService.ServiceReference1.mod();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            WebService.ServiceReference1.modResponse retVal = ((WebService.ServiceReference1.CalcSEI)(this)).mod(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebService.ServiceReference1.modResponse> WebService.ServiceReference1.CalcSEI.modAsync(WebService.ServiceReference1.mod request) {
            return base.Channel.modAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebService.ServiceReference1.modResponse> modAsync(int arg0, int arg1) {
            WebService.ServiceReference1.mod inValue = new WebService.ServiceReference1.mod();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((WebService.ServiceReference1.CalcSEI)(this)).modAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebService.ServiceReference1.addResponse WebService.ServiceReference1.CalcSEI.add(WebService.ServiceReference1.add request) {
            return base.Channel.add(request);
        }
        
        public double add(double arg0, double arg1) {
            WebService.ServiceReference1.add inValue = new WebService.ServiceReference1.add();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            WebService.ServiceReference1.addResponse retVal = ((WebService.ServiceReference1.CalcSEI)(this)).add(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebService.ServiceReference1.addResponse> WebService.ServiceReference1.CalcSEI.addAsync(WebService.ServiceReference1.add request) {
            return base.Channel.addAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebService.ServiceReference1.addResponse> addAsync(double arg0, double arg1) {
            WebService.ServiceReference1.add inValue = new WebService.ServiceReference1.add();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((WebService.ServiceReference1.CalcSEI)(this)).addAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebService.ServiceReference1.divResponse WebService.ServiceReference1.CalcSEI.div(WebService.ServiceReference1.div request) {
            return base.Channel.div(request);
        }
        
        public double div(double arg0, double arg1) {
            WebService.ServiceReference1.div inValue = new WebService.ServiceReference1.div();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            WebService.ServiceReference1.divResponse retVal = ((WebService.ServiceReference1.CalcSEI)(this)).div(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebService.ServiceReference1.divResponse> WebService.ServiceReference1.CalcSEI.divAsync(WebService.ServiceReference1.div request) {
            return base.Channel.divAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebService.ServiceReference1.divResponse> divAsync(double arg0, double arg1) {
            WebService.ServiceReference1.div inValue = new WebService.ServiceReference1.div();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((WebService.ServiceReference1.CalcSEI)(this)).divAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebService.ServiceReference1.subResponse WebService.ServiceReference1.CalcSEI.sub(WebService.ServiceReference1.sub request) {
            return base.Channel.sub(request);
        }
        
        public double sub(double arg0, double arg1) {
            WebService.ServiceReference1.sub inValue = new WebService.ServiceReference1.sub();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            WebService.ServiceReference1.subResponse retVal = ((WebService.ServiceReference1.CalcSEI)(this)).sub(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebService.ServiceReference1.subResponse> WebService.ServiceReference1.CalcSEI.subAsync(WebService.ServiceReference1.sub request) {
            return base.Channel.subAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebService.ServiceReference1.subResponse> subAsync(double arg0, double arg1) {
            WebService.ServiceReference1.sub inValue = new WebService.ServiceReference1.sub();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((WebService.ServiceReference1.CalcSEI)(this)).subAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebService.ServiceReference1.factorialResponse WebService.ServiceReference1.CalcSEI.factorial(WebService.ServiceReference1.factorial request) {
            return base.Channel.factorial(request);
        }
        
        public long factorial(int arg0) {
            WebService.ServiceReference1.factorial inValue = new WebService.ServiceReference1.factorial();
            inValue.arg0 = arg0;
            WebService.ServiceReference1.factorialResponse retVal = ((WebService.ServiceReference1.CalcSEI)(this)).factorial(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebService.ServiceReference1.factorialResponse> WebService.ServiceReference1.CalcSEI.factorialAsync(WebService.ServiceReference1.factorial request) {
            return base.Channel.factorialAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebService.ServiceReference1.factorialResponse> factorialAsync(int arg0) {
            WebService.ServiceReference1.factorial inValue = new WebService.ServiceReference1.factorial();
            inValue.arg0 = arg0;
            return ((WebService.ServiceReference1.CalcSEI)(this)).factorialAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebService.ServiceReference1.mulResponse WebService.ServiceReference1.CalcSEI.mul(WebService.ServiceReference1.mul request) {
            return base.Channel.mul(request);
        }
        
        public double mul(double arg0, double arg1) {
            WebService.ServiceReference1.mul inValue = new WebService.ServiceReference1.mul();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            WebService.ServiceReference1.mulResponse retVal = ((WebService.ServiceReference1.CalcSEI)(this)).mul(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebService.ServiceReference1.mulResponse> WebService.ServiceReference1.CalcSEI.mulAsync(WebService.ServiceReference1.mul request) {
            return base.Channel.mulAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebService.ServiceReference1.mulResponse> mulAsync(double arg0, double arg1) {
            WebService.ServiceReference1.mul inValue = new WebService.ServiceReference1.mul();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((WebService.ServiceReference1.CalcSEI)(this)).mulAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebService.ServiceReference1.sqrResponse WebService.ServiceReference1.CalcSEI.sqr(WebService.ServiceReference1.sqr request) {
            return base.Channel.sqr(request);
        }
        
        public double sqr(double arg0) {
            WebService.ServiceReference1.sqr inValue = new WebService.ServiceReference1.sqr();
            inValue.arg0 = arg0;
            WebService.ServiceReference1.sqrResponse retVal = ((WebService.ServiceReference1.CalcSEI)(this)).sqr(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebService.ServiceReference1.sqrResponse> WebService.ServiceReference1.CalcSEI.sqrAsync(WebService.ServiceReference1.sqr request) {
            return base.Channel.sqrAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebService.ServiceReference1.sqrResponse> sqrAsync(double arg0) {
            WebService.ServiceReference1.sqr inValue = new WebService.ServiceReference1.sqr();
            inValue.arg0 = arg0;
            return ((WebService.ServiceReference1.CalcSEI)(this)).sqrAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebService.ServiceReference1.sqrtResponse WebService.ServiceReference1.CalcSEI.sqrt(WebService.ServiceReference1.sqrt request) {
            return base.Channel.sqrt(request);
        }
        
        public double sqrt(double arg0) {
            WebService.ServiceReference1.sqrt inValue = new WebService.ServiceReference1.sqrt();
            inValue.arg0 = arg0;
            WebService.ServiceReference1.sqrtResponse retVal = ((WebService.ServiceReference1.CalcSEI)(this)).sqrt(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebService.ServiceReference1.sqrtResponse> WebService.ServiceReference1.CalcSEI.sqrtAsync(WebService.ServiceReference1.sqrt request) {
            return base.Channel.sqrtAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebService.ServiceReference1.sqrtResponse> sqrtAsync(double arg0) {
            WebService.ServiceReference1.sqrt inValue = new WebService.ServiceReference1.sqrt();
            inValue.arg0 = arg0;
            return ((WebService.ServiceReference1.CalcSEI)(this)).sqrtAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebService.ServiceReference1.aboutResponse WebService.ServiceReference1.CalcSEI.about(WebService.ServiceReference1.about request) {
            return base.Channel.about(request);
        }
        
        public string about(string arg0) {
            WebService.ServiceReference1.about inValue = new WebService.ServiceReference1.about();
            inValue.Body = new WebService.ServiceReference1.aboutBody();
            inValue.Body.arg0 = arg0;
            WebService.ServiceReference1.aboutResponse retVal = ((WebService.ServiceReference1.CalcSEI)(this)).about(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebService.ServiceReference1.aboutResponse> WebService.ServiceReference1.CalcSEI.aboutAsync(WebService.ServiceReference1.about request) {
            return base.Channel.aboutAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebService.ServiceReference1.aboutResponse> aboutAsync(string arg0) {
            WebService.ServiceReference1.about inValue = new WebService.ServiceReference1.about();
            inValue.Body = new WebService.ServiceReference1.aboutBody();
            inValue.Body.arg0 = arg0;
            return ((WebService.ServiceReference1.CalcSEI)(this)).aboutAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebService.ServiceReference1.powResponse WebService.ServiceReference1.CalcSEI.pow(WebService.ServiceReference1.pow request) {
            return base.Channel.pow(request);
        }
        
        public double pow(double arg0, double arg1) {
            WebService.ServiceReference1.pow inValue = new WebService.ServiceReference1.pow();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            WebService.ServiceReference1.powResponse retVal = ((WebService.ServiceReference1.CalcSEI)(this)).pow(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebService.ServiceReference1.powResponse> WebService.ServiceReference1.CalcSEI.powAsync(WebService.ServiceReference1.pow request) {
            return base.Channel.powAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebService.ServiceReference1.powResponse> powAsync(double arg0, double arg1) {
            WebService.ServiceReference1.pow inValue = new WebService.ServiceReference1.pow();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((WebService.ServiceReference1.CalcSEI)(this)).powAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebService.ServiceReference1.div1Response WebService.ServiceReference1.CalcSEI.div1(WebService.ServiceReference1.div1 request) {
            return base.Channel.div1(request);
        }
        
        public int div1(int arg0, int arg1) {
            WebService.ServiceReference1.div1 inValue = new WebService.ServiceReference1.div1();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            WebService.ServiceReference1.div1Response retVal = ((WebService.ServiceReference1.CalcSEI)(this)).div1(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebService.ServiceReference1.div1Response> WebService.ServiceReference1.CalcSEI.div1Async(WebService.ServiceReference1.div1 request) {
            return base.Channel.div1Async(request);
        }
        
        public System.Threading.Tasks.Task<WebService.ServiceReference1.div1Response> div1Async(int arg0, int arg1) {
            WebService.ServiceReference1.div1 inValue = new WebService.ServiceReference1.div1();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((WebService.ServiceReference1.CalcSEI)(this)).div1Async(inValue);
        }
    }
}
