//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorTestClient.CalculatorService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://edu.softserve.com/", ConfigurationName="CalculatorService.CalcSEI")]
    public interface CalcSEI {
        
        // CODEGEN: Generating message contract since message part namespace () does not match the default value (http://edu.softserve.com/)
        [System.ServiceModel.OperationContractAttribute(Action="urn:Mod", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CalculatorTestClient.CalculatorService.modResponse mod(CalculatorTestClient.CalculatorService.mod request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Mod", ReplyAction="*")]
        System.Threading.Tasks.Task<CalculatorTestClient.CalculatorService.modResponse> modAsync(CalculatorTestClient.CalculatorService.mod request);
        
        // CODEGEN: Generating message contract since message part namespace () does not match the default value (http://edu.softserve.com/)
        [System.ServiceModel.OperationContractAttribute(Action="urn:Add", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CalculatorTestClient.CalculatorService.addResponse add(CalculatorTestClient.CalculatorService.add request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Add", ReplyAction="*")]
        System.Threading.Tasks.Task<CalculatorTestClient.CalculatorService.addResponse> addAsync(CalculatorTestClient.CalculatorService.add request);
        
        // CODEGEN: Generating message contract since message part namespace () does not match the default value (http://edu.softserve.com/)
        [System.ServiceModel.OperationContractAttribute(Action="urn:Div", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CalculatorTestClient.CalculatorService.divResponse div(CalculatorTestClient.CalculatorService.div request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Div", ReplyAction="*")]
        System.Threading.Tasks.Task<CalculatorTestClient.CalculatorService.divResponse> divAsync(CalculatorTestClient.CalculatorService.div request);
        
        // CODEGEN: Generating message contract since message part namespace () does not match the default value (http://edu.softserve.com/)
        [System.ServiceModel.OperationContractAttribute(Action="urn:Sub", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CalculatorTestClient.CalculatorService.subResponse sub(CalculatorTestClient.CalculatorService.sub request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Sub", ReplyAction="*")]
        System.Threading.Tasks.Task<CalculatorTestClient.CalculatorService.subResponse> subAsync(CalculatorTestClient.CalculatorService.sub request);
        
        // CODEGEN: Generating message contract since message part namespace () does not match the default value (http://edu.softserve.com/)
        [System.ServiceModel.OperationContractAttribute(Action="urn:Factorial", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CalculatorTestClient.CalculatorService.factorialResponse factorial(CalculatorTestClient.CalculatorService.factorial request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Factorial", ReplyAction="*")]
        System.Threading.Tasks.Task<CalculatorTestClient.CalculatorService.factorialResponse> factorialAsync(CalculatorTestClient.CalculatorService.factorial request);
        
        // CODEGEN: Generating message contract since message part namespace () does not match the default value (http://edu.softserve.com/)
        [System.ServiceModel.OperationContractAttribute(Action="urn:Mul", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CalculatorTestClient.CalculatorService.mulResponse mul(CalculatorTestClient.CalculatorService.mul request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Mul", ReplyAction="*")]
        System.Threading.Tasks.Task<CalculatorTestClient.CalculatorService.mulResponse> mulAsync(CalculatorTestClient.CalculatorService.mul request);
        
        // CODEGEN: Generating message contract since message part namespace () does not match the default value (http://edu.softserve.com/)
        [System.ServiceModel.OperationContractAttribute(Action="urn:Sqr", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CalculatorTestClient.CalculatorService.sqrResponse sqr(CalculatorTestClient.CalculatorService.sqr request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Sqr", ReplyAction="*")]
        System.Threading.Tasks.Task<CalculatorTestClient.CalculatorService.sqrResponse> sqrAsync(CalculatorTestClient.CalculatorService.sqr request);
        
        // CODEGEN: Generating message contract since message part namespace () does not match the default value (http://edu.softserve.com/)
        [System.ServiceModel.OperationContractAttribute(Action="urn:Sqrt", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CalculatorTestClient.CalculatorService.sqrtResponse sqrt(CalculatorTestClient.CalculatorService.sqrt request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Sqrt", ReplyAction="*")]
        System.Threading.Tasks.Task<CalculatorTestClient.CalculatorService.sqrtResponse> sqrtAsync(CalculatorTestClient.CalculatorService.sqrt request);
        
        // CODEGEN: Generating message contract since element name arg0 from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="urn:About", ReplyAction="*")]
        CalculatorTestClient.CalculatorService.aboutResponse about(CalculatorTestClient.CalculatorService.about request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:About", ReplyAction="*")]
        System.Threading.Tasks.Task<CalculatorTestClient.CalculatorService.aboutResponse> aboutAsync(CalculatorTestClient.CalculatorService.about request);
        
        // CODEGEN: Generating message contract since message part namespace () does not match the default value (http://edu.softserve.com/)
        [System.ServiceModel.OperationContractAttribute(Action="urn:Pow", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CalculatorTestClient.CalculatorService.powResponse pow(CalculatorTestClient.CalculatorService.pow request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Pow", ReplyAction="*")]
        System.Threading.Tasks.Task<CalculatorTestClient.CalculatorService.powResponse> powAsync(CalculatorTestClient.CalculatorService.pow request);
        
        // CODEGEN: Generating message contract since the wrapper name (divResponse1) of message div1Response does not match the default value (div1)
        [System.ServiceModel.OperationContractAttribute(Action="urn:Div1", ReplyAction="*")]
        CalculatorTestClient.CalculatorService.div1Response div1(CalculatorTestClient.CalculatorService.div1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Div1", ReplyAction="*")]
        System.Threading.Tasks.Task<CalculatorTestClient.CalculatorService.div1Response> div1Async(CalculatorTestClient.CalculatorService.div1 request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="mod", WrapperNamespace="http://edu.softserve.com/", IsWrapped=true)]
    public partial class mod {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public int arg1;
        
        public mod() {
        }
        
        public mod(int arg0, int arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modResponse", WrapperNamespace="http://edu.softserve.com/", IsWrapped=true)]
    public partial class modResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int @return;
        
        public modResponse() {
        }
        
        public modResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="add", WrapperNamespace="http://edu.softserve.com/", IsWrapped=true)]
    public partial class add {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public double arg1;
        
        public add() {
        }
        
        public add(double arg0, double arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addResponse", WrapperNamespace="http://edu.softserve.com/", IsWrapped=true)]
    public partial class addResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double @return;
        
        public addResponse() {
        }
        
        public addResponse(double @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="div", WrapperNamespace="http://edu.softserve.com/", IsWrapped=true)]
    public partial class div {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public double arg1;
        
        public div() {
        }
        
        public div(double arg0, double arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="divResponse", WrapperNamespace="http://edu.softserve.com/", IsWrapped=true)]
    public partial class divResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double @return;
        
        public divResponse() {
        }
        
        public divResponse(double @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sub", WrapperNamespace="http://edu.softserve.com/", IsWrapped=true)]
    public partial class sub {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public double arg1;
        
        public sub() {
        }
        
        public sub(double arg0, double arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="subResponse", WrapperNamespace="http://edu.softserve.com/", IsWrapped=true)]
    public partial class subResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double @return;
        
        public subResponse() {
        }
        
        public subResponse(double @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="factorial", WrapperNamespace="http://edu.softserve.com/", IsWrapped=true)]
    public partial class factorial {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int arg0;
        
        public factorial() {
        }
        
        public factorial(int arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="factorialResponse", WrapperNamespace="http://edu.softserve.com/", IsWrapped=true)]
    public partial class factorialResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public long @return;
        
        public factorialResponse() {
        }
        
        public factorialResponse(long @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="mul", WrapperNamespace="http://edu.softserve.com/", IsWrapped=true)]
    public partial class mul {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public double arg1;
        
        public mul() {
        }
        
        public mul(double arg0, double arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="mulResponse", WrapperNamespace="http://edu.softserve.com/", IsWrapped=true)]
    public partial class mulResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double @return;
        
        public mulResponse() {
        }
        
        public mulResponse(double @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sqr", WrapperNamespace="http://edu.softserve.com/", IsWrapped=true)]
    public partial class sqr {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double arg0;
        
        public sqr() {
        }
        
        public sqr(double arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sqrResponse", WrapperNamespace="http://edu.softserve.com/", IsWrapped=true)]
    public partial class sqrResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double @return;
        
        public sqrResponse() {
        }
        
        public sqrResponse(double @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sqrt", WrapperNamespace="http://edu.softserve.com/", IsWrapped=true)]
    public partial class sqrt {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double arg0;
        
        public sqrt() {
        }
        
        public sqrt(double arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sqrtResponse", WrapperNamespace="http://edu.softserve.com/", IsWrapped=true)]
    public partial class sqrtResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double @return;
        
        public sqrtResponse() {
        }
        
        public sqrtResponse(double @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class about {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="about", Namespace="http://edu.softserve.com/", Order=0)]
        public CalculatorTestClient.CalculatorService.aboutBody Body;
        
        public about() {
        }
        
        public about(CalculatorTestClient.CalculatorService.aboutBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class aboutBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        public aboutBody() {
        }
        
        public aboutBody(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class aboutResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="aboutResponse", Namespace="http://edu.softserve.com/", Order=0)]
        public CalculatorTestClient.CalculatorService.aboutResponseBody Body;
        
        public aboutResponse() {
        }
        
        public aboutResponse(CalculatorTestClient.CalculatorService.aboutResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class aboutResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public aboutResponseBody() {
        }
        
        public aboutResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="pow", WrapperNamespace="http://edu.softserve.com/", IsWrapped=true)]
    public partial class pow {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public double arg1;
        
        public pow() {
        }
        
        public pow(double arg0, double arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="powResponse", WrapperNamespace="http://edu.softserve.com/", IsWrapped=true)]
    public partial class powResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double @return;
        
        public powResponse() {
        }
        
        public powResponse(double @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="div1", WrapperNamespace="http://edu.softserve.com/", IsWrapped=true)]
    public partial class div1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public int arg1;
        
        public div1() {
        }
        
        public div1(int arg0, int arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="divResponse1", WrapperNamespace="http://edu.softserve.com/", IsWrapped=true)]
    public partial class div1Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int @return;
        
        public div1Response() {
        }
        
        public div1Response(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CalcSEIChannel : CalculatorTestClient.CalculatorService.CalcSEI, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalcSEIClient : System.ServiceModel.ClientBase<CalculatorTestClient.CalculatorService.CalcSEI>, CalculatorTestClient.CalculatorService.CalcSEI {
        
        public CalcSEIClient() {
        }
        
        public CalcSEIClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CalcSEIClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalcSEIClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalcSEIClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CalculatorTestClient.CalculatorService.modResponse CalculatorTestClient.CalculatorService.CalcSEI.mod(CalculatorTestClient.CalculatorService.mod request) {
            return base.Channel.mod(request);
        }
        
        public int mod(int arg0, int arg1) {
            CalculatorTestClient.CalculatorService.mod inValue = new CalculatorTestClient.CalculatorService.mod();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            CalculatorTestClient.CalculatorService.modResponse retVal = ((CalculatorTestClient.CalculatorService.CalcSEI)(this)).mod(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CalculatorTestClient.CalculatorService.modResponse> CalculatorTestClient.CalculatorService.CalcSEI.modAsync(CalculatorTestClient.CalculatorService.mod request) {
            return base.Channel.modAsync(request);
        }
        
        public System.Threading.Tasks.Task<CalculatorTestClient.CalculatorService.modResponse> modAsync(int arg0, int arg1) {
            CalculatorTestClient.CalculatorService.mod inValue = new CalculatorTestClient.CalculatorService.mod();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((CalculatorTestClient.CalculatorService.CalcSEI)(this)).modAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CalculatorTestClient.CalculatorService.addResponse CalculatorTestClient.CalculatorService.CalcSEI.add(CalculatorTestClient.CalculatorService.add request) {
            return base.Channel.add(request);
        }
        
        public double add(double arg0, double arg1) {
            CalculatorTestClient.CalculatorService.add inValue = new CalculatorTestClient.CalculatorService.add();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            CalculatorTestClient.CalculatorService.addResponse retVal = ((CalculatorTestClient.CalculatorService.CalcSEI)(this)).add(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CalculatorTestClient.CalculatorService.addResponse> CalculatorTestClient.CalculatorService.CalcSEI.addAsync(CalculatorTestClient.CalculatorService.add request) {
            return base.Channel.addAsync(request);
        }
        
        public System.Threading.Tasks.Task<CalculatorTestClient.CalculatorService.addResponse> addAsync(double arg0, double arg1) {
            CalculatorTestClient.CalculatorService.add inValue = new CalculatorTestClient.CalculatorService.add();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((CalculatorTestClient.CalculatorService.CalcSEI)(this)).addAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CalculatorTestClient.CalculatorService.divResponse CalculatorTestClient.CalculatorService.CalcSEI.div(CalculatorTestClient.CalculatorService.div request) {
            return base.Channel.div(request);
        }
        
        public double div(double arg0, double arg1) {
            CalculatorTestClient.CalculatorService.div inValue = new CalculatorTestClient.CalculatorService.div();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            CalculatorTestClient.CalculatorService.divResponse retVal = ((CalculatorTestClient.CalculatorService.CalcSEI)(this)).div(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CalculatorTestClient.CalculatorService.divResponse> CalculatorTestClient.CalculatorService.CalcSEI.divAsync(CalculatorTestClient.CalculatorService.div request) {
            return base.Channel.divAsync(request);
        }
        
        public System.Threading.Tasks.Task<CalculatorTestClient.CalculatorService.divResponse> divAsync(double arg0, double arg1) {
            CalculatorTestClient.CalculatorService.div inValue = new CalculatorTestClient.CalculatorService.div();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((CalculatorTestClient.CalculatorService.CalcSEI)(this)).divAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CalculatorTestClient.CalculatorService.subResponse CalculatorTestClient.CalculatorService.CalcSEI.sub(CalculatorTestClient.CalculatorService.sub request) {
            return base.Channel.sub(request);
        }
        
        public double sub(double arg0, double arg1) {
            CalculatorTestClient.CalculatorService.sub inValue = new CalculatorTestClient.CalculatorService.sub();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            CalculatorTestClient.CalculatorService.subResponse retVal = ((CalculatorTestClient.CalculatorService.CalcSEI)(this)).sub(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CalculatorTestClient.CalculatorService.subResponse> CalculatorTestClient.CalculatorService.CalcSEI.subAsync(CalculatorTestClient.CalculatorService.sub request) {
            return base.Channel.subAsync(request);
        }
        
        public System.Threading.Tasks.Task<CalculatorTestClient.CalculatorService.subResponse> subAsync(double arg0, double arg1) {
            CalculatorTestClient.CalculatorService.sub inValue = new CalculatorTestClient.CalculatorService.sub();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((CalculatorTestClient.CalculatorService.CalcSEI)(this)).subAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CalculatorTestClient.CalculatorService.factorialResponse CalculatorTestClient.CalculatorService.CalcSEI.factorial(CalculatorTestClient.CalculatorService.factorial request) {
            return base.Channel.factorial(request);
        }
        
        public long factorial(int arg0) {
            CalculatorTestClient.CalculatorService.factorial inValue = new CalculatorTestClient.CalculatorService.factorial();
            inValue.arg0 = arg0;
            CalculatorTestClient.CalculatorService.factorialResponse retVal = ((CalculatorTestClient.CalculatorService.CalcSEI)(this)).factorial(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CalculatorTestClient.CalculatorService.factorialResponse> CalculatorTestClient.CalculatorService.CalcSEI.factorialAsync(CalculatorTestClient.CalculatorService.factorial request) {
            return base.Channel.factorialAsync(request);
        }
        
        public System.Threading.Tasks.Task<CalculatorTestClient.CalculatorService.factorialResponse> factorialAsync(int arg0) {
            CalculatorTestClient.CalculatorService.factorial inValue = new CalculatorTestClient.CalculatorService.factorial();
            inValue.arg0 = arg0;
            return ((CalculatorTestClient.CalculatorService.CalcSEI)(this)).factorialAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CalculatorTestClient.CalculatorService.mulResponse CalculatorTestClient.CalculatorService.CalcSEI.mul(CalculatorTestClient.CalculatorService.mul request) {
            return base.Channel.mul(request);
        }
        
        public double mul(double arg0, double arg1) {
            CalculatorTestClient.CalculatorService.mul inValue = new CalculatorTestClient.CalculatorService.mul();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            CalculatorTestClient.CalculatorService.mulResponse retVal = ((CalculatorTestClient.CalculatorService.CalcSEI)(this)).mul(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CalculatorTestClient.CalculatorService.mulResponse> CalculatorTestClient.CalculatorService.CalcSEI.mulAsync(CalculatorTestClient.CalculatorService.mul request) {
            return base.Channel.mulAsync(request);
        }
        
        public System.Threading.Tasks.Task<CalculatorTestClient.CalculatorService.mulResponse> mulAsync(double arg0, double arg1) {
            CalculatorTestClient.CalculatorService.mul inValue = new CalculatorTestClient.CalculatorService.mul();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((CalculatorTestClient.CalculatorService.CalcSEI)(this)).mulAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CalculatorTestClient.CalculatorService.sqrResponse CalculatorTestClient.CalculatorService.CalcSEI.sqr(CalculatorTestClient.CalculatorService.sqr request) {
            return base.Channel.sqr(request);
        }
        
        public double sqr(double arg0) {
            CalculatorTestClient.CalculatorService.sqr inValue = new CalculatorTestClient.CalculatorService.sqr();
            inValue.arg0 = arg0;
            CalculatorTestClient.CalculatorService.sqrResponse retVal = ((CalculatorTestClient.CalculatorService.CalcSEI)(this)).sqr(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CalculatorTestClient.CalculatorService.sqrResponse> CalculatorTestClient.CalculatorService.CalcSEI.sqrAsync(CalculatorTestClient.CalculatorService.sqr request) {
            return base.Channel.sqrAsync(request);
        }
        
        public System.Threading.Tasks.Task<CalculatorTestClient.CalculatorService.sqrResponse> sqrAsync(double arg0) {
            CalculatorTestClient.CalculatorService.sqr inValue = new CalculatorTestClient.CalculatorService.sqr();
            inValue.arg0 = arg0;
            return ((CalculatorTestClient.CalculatorService.CalcSEI)(this)).sqrAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CalculatorTestClient.CalculatorService.sqrtResponse CalculatorTestClient.CalculatorService.CalcSEI.sqrt(CalculatorTestClient.CalculatorService.sqrt request) {
            return base.Channel.sqrt(request);
        }
        
        public double sqrt(double arg0) {
            CalculatorTestClient.CalculatorService.sqrt inValue = new CalculatorTestClient.CalculatorService.sqrt();
            inValue.arg0 = arg0;
            CalculatorTestClient.CalculatorService.sqrtResponse retVal = ((CalculatorTestClient.CalculatorService.CalcSEI)(this)).sqrt(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CalculatorTestClient.CalculatorService.sqrtResponse> CalculatorTestClient.CalculatorService.CalcSEI.sqrtAsync(CalculatorTestClient.CalculatorService.sqrt request) {
            return base.Channel.sqrtAsync(request);
        }
        
        public System.Threading.Tasks.Task<CalculatorTestClient.CalculatorService.sqrtResponse> sqrtAsync(double arg0) {
            CalculatorTestClient.CalculatorService.sqrt inValue = new CalculatorTestClient.CalculatorService.sqrt();
            inValue.arg0 = arg0;
            return ((CalculatorTestClient.CalculatorService.CalcSEI)(this)).sqrtAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CalculatorTestClient.CalculatorService.aboutResponse CalculatorTestClient.CalculatorService.CalcSEI.about(CalculatorTestClient.CalculatorService.about request) {
            return base.Channel.about(request);
        }
        
        public string about(string arg0) {
            CalculatorTestClient.CalculatorService.about inValue = new CalculatorTestClient.CalculatorService.about();
            inValue.Body = new CalculatorTestClient.CalculatorService.aboutBody();
            inValue.Body.arg0 = arg0;
            CalculatorTestClient.CalculatorService.aboutResponse retVal = ((CalculatorTestClient.CalculatorService.CalcSEI)(this)).about(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CalculatorTestClient.CalculatorService.aboutResponse> CalculatorTestClient.CalculatorService.CalcSEI.aboutAsync(CalculatorTestClient.CalculatorService.about request) {
            return base.Channel.aboutAsync(request);
        }
        
        public System.Threading.Tasks.Task<CalculatorTestClient.CalculatorService.aboutResponse> aboutAsync(string arg0) {
            CalculatorTestClient.CalculatorService.about inValue = new CalculatorTestClient.CalculatorService.about();
            inValue.Body = new CalculatorTestClient.CalculatorService.aboutBody();
            inValue.Body.arg0 = arg0;
            return ((CalculatorTestClient.CalculatorService.CalcSEI)(this)).aboutAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CalculatorTestClient.CalculatorService.powResponse CalculatorTestClient.CalculatorService.CalcSEI.pow(CalculatorTestClient.CalculatorService.pow request) {
            return base.Channel.pow(request);
        }
        
        public double pow(double arg0, double arg1) {
            CalculatorTestClient.CalculatorService.pow inValue = new CalculatorTestClient.CalculatorService.pow();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            CalculatorTestClient.CalculatorService.powResponse retVal = ((CalculatorTestClient.CalculatorService.CalcSEI)(this)).pow(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CalculatorTestClient.CalculatorService.powResponse> CalculatorTestClient.CalculatorService.CalcSEI.powAsync(CalculatorTestClient.CalculatorService.pow request) {
            return base.Channel.powAsync(request);
        }
        
        public System.Threading.Tasks.Task<CalculatorTestClient.CalculatorService.powResponse> powAsync(double arg0, double arg1) {
            CalculatorTestClient.CalculatorService.pow inValue = new CalculatorTestClient.CalculatorService.pow();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((CalculatorTestClient.CalculatorService.CalcSEI)(this)).powAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CalculatorTestClient.CalculatorService.div1Response CalculatorTestClient.CalculatorService.CalcSEI.div1(CalculatorTestClient.CalculatorService.div1 request) {
            return base.Channel.div1(request);
        }
        
        public int div1(int arg0, int arg1) {
            CalculatorTestClient.CalculatorService.div1 inValue = new CalculatorTestClient.CalculatorService.div1();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            CalculatorTestClient.CalculatorService.div1Response retVal = ((CalculatorTestClient.CalculatorService.CalcSEI)(this)).div1(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CalculatorTestClient.CalculatorService.div1Response> CalculatorTestClient.CalculatorService.CalcSEI.div1Async(CalculatorTestClient.CalculatorService.div1 request) {
            return base.Channel.div1Async(request);
        }
        
        public System.Threading.Tasks.Task<CalculatorTestClient.CalculatorService.div1Response> div1Async(int arg0, int arg1) {
            CalculatorTestClient.CalculatorService.div1 inValue = new CalculatorTestClient.CalculatorService.div1();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((CalculatorTestClient.CalculatorService.CalcSEI)(this)).div1Async(inValue);
        }
    }
}
